title: Kalhan Boralessa
description: PhD Researcher in Cooperative Perception & Multi-Robot Systems
author: Kalhan Boralessa

# Social links
linkedin_username: kalhansb
github_username: kalhansb
google_scholar: 6-OKLyIAAAAJ

# Build settings
theme: minima

# Additional settings
show_excerpts: true
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/kalhansb" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/kalhansb/" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?hl=en&user=6-OKLyIAAAAJ&view_op=list_works&sortby=pubdate" }
